name: Check

on: [pull_request]

jobs:
  check:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - uses: browser-actions/setup-chrome@latest
      - run: CHROME_EXECUTABLE_PATH=$(which chrome) bundle exec rspec --format documentation
        timeout-minutes: 45
